language: go
go:
- 1.14.x
addons:
  apt:
    packages:
    - python3
before_deploy:
- python3 ./build.py -build
deploy:
  provider: releases
  api_key:
    secure: PZf/ia54WY843VMczoleJfXHQDlKMyhiiFR/7ZgIFjs6Scw+VCICvCdPzgDQqZtIujHYosPLpF9S/SOXvF1uSHMTJS2wY8MAz404MdzH19QN+wbGkA1Pwt1zrkfIIGSpd2Wwy141FB/UXxdurD+/0Y2zo47p9/97RZ85vdDaNrvGA2pJIiOm7MBMzgq9WQ4a75ZVq46v8BrUtwublNly6rVpAWJvTK0gSK43ImQuN9VotO/3MTIcMF/I8LfKkBCmbZvQPPSEo5k5oWPXxpQo7Wc+IOzQtuAftCY0LjMN3xg+HTLyCsFOnkw4VWu2WkAeaM2b04sEZYZcG9skyNv1JrDRCIonQ+fcp6jtvqBojOij3RUNp4XRUXhjKWkleUGMjvXCCV5RtpXfmAF6FRqP7eI6hXmlkGYjv9leK3uwC+mQ9kq1SIdHRGIbxPQfhEmzRiHQnrKo62CaF4N0KuY6S6B7gqR2m1ehaZdGLOUEImH2hfaVDH/JclNEj3fW2Qw0+wASDHNQd6rzZB+0bCmyTn0G2lyqlx53pL63UAqoCm+svGH/NZDMnSsHQSFy50LqkgUOP069HKbpArfUr7R9Kdb7cJu+3CJPoD2tUyXzA8/I1ij59WD9WANjt6qOgJWiBzPeJvMKnZcipxssocSCUdLJOlMAkMVsV1pLnlXELpk=
  file: output/*
  skip_cleanup: true
  on:
    tags: true
